### PR TITLE
Update MachineLearning_Engine.csproj

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes compliance of Machine Learning Toolkit. This is impacting beta creation.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 2884575028

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by JohannaOlin1 — APPROVED** [review]
LGTM

**Pull request merged**
